# Generated by Django 4.0.4 on 2022-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_rename_upload_userupload_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='uploaded_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='uploaded_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
