# Generated by Django 4.0.4 on 2022-05-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_userupload_uploaded_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='uploaded_image',
        ),
    ]
