# Generated by Django 4.0.4 on 2022-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_userupload_uploaded_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='date_of_upload',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userupload',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userupload',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
