# Generated by Django 4.0.4 on 2022-05-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_userupload_date_of_upload_userupload_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='content_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
