# Generated by Django 4.0.4 on 2022-05-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_userupload_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesModel',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'activities_table',
            },
        ),
    ]
