# Generated by Django 4.0.4 on 2022-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_activitiesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesmodel',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
