# Generated by Django 4.0.4 on 2022-05-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_activitiesmodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesmodel',
            name='action',
            field=models.CharField(default='uploaded', max_length=100),
        ),
    ]
