# Generated by Django 4.0.4 on 2022-05-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_activitiesmodel_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesmodel',
            name='owner_id',
            field=models.IntegerField(null=True),
        ),
    ]
