# Generated by Django 4.0.4 on 2022-05-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_activitiesmodel_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitiesmodel',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
