# Generated by Django 4.0.4 on 2022-05-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_activitiesmodel_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiesmodel',
            old_name='otp',
            new_name='key',
        ),
    ]
